config/routes.rb
AskmeModel::Application.routes.draw do
  root :to => 'respondents#index'

  devise_for :respondents, :controllers => { :sessions => "respondents/sessions", :registrations => "respondents/registrations", :omniauth_callbacks => "respondents/omniauth_callbacks" }
  devise_for :responds, :controller => "fake_questions"

  match 'profile' => 'respondents#show'
  match 'profile/edit/' => 'respondents#edit#:id', :as => "pr_edit"

  resources :respondents do
    resources :profiles do
      member do
        post 'social_demographic_settings', :as => :sd
        post 'business_settings', :as => :business
      end          
    end
  end

  match 'surveys/:id/edit/page/:pagenumber' => 'surveys#edit#:id', :as => "survey_edit_page"

  match 'submitAnswers' => 'fakeQuestions#submitAnswers', :as => 'sa'

  resources :surveys do
    resources :pages do
      resources :questions do 
        
      end
    end
  end










 

end

app/models/survey_structure/survey.rb
class Survey
  include MongoMapper::Document

  connection(Mongo::Connection.new('localhost', 27017))
  set_database_name "surveys-#{Rails.env}"
  
  key :title, String
  key :description, String
  key :active, Boolean
  key :expires, Date

  many :pages
  
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
	
	def index
		@surveyTitle = "Test Survey"
		@questionList = [
			{:id => 1, :title => "Question1", :answers => ["answer1", "answer2"] },
			{:id => 2, :title => "Question2", :answers => ["answer1", "answer2"] },
			{:id => 3, :title => "Question3", :answers => ["answer1", "answer2"] },
			{:id => 4, :title => "Question4", :answers => ["answer1", "answer2"] }
		]
		@noheader = true
	end
	# survey should has default page in instantiation process
	def new
		@survey = Survey.new
		respond_to do |format|
	        format.html {render html: new_survey_path}
      		format.json { render json: @survey }
	    end
	end
	
	def create
		@survey = Survey.new(params[:survey])
		@survey.pages << add_default_page
		
		respond_to do |format|
			if(@survey.save!)
				format.html { redirect_to edit_survey_path(@survey), :notice => "Settings were successfully saved" }
    		    format.json { head :no_content }
			else
				format.html { render action: "new" }
		        format.json { render json: @survey.errors, status: :unprocessable_entity }
			end					
		end
	end

	def edit
		@survey = Survey.find(params[:id])
		@curPage = params[:pagenumber] || 1
		
		if @curPage == 1 && !params[:pagenumber]
			@actTab = false
		else
			@actTab = true
		end
		respond_to do |format|
	        format.html # show.html.erb
      		format.json { render json: @survey }
	    end
	end

	def update
		@survey = Survey.find(params[:id])
		@curPage = params[:pagenumber] || 1
		respond_to do |format|
	      if @survey.update_attributes(params[:survey])
	        format.html { redirect_to survey_edit_page_path(@survey, @curPage), :notice => "Settings were successfully saved" }
	        format.json { head :no_content }
	      else
	        format.html { render action: "edit" }
	        format.json { render json: @survey.errors, status: :unprocessable_entity }
	      end
	    end
	end

	private 
		def add_default_page()
			Page.new(:title=>'Default Page', :description=>'You can add new pages!', :page_number=>1)
 		end			
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/views/surveys/_basic_form.html.erb
<div class="row">
	<div class="eight columns" style="background-color: #f4f4f4;">
				<div style="padding: 1% 4% 0; ">
					<%= form.label :title, "1. Название", :style=>'font-weight:bold' %><br />
				<%= form.text_field :title, :class=>'input-text' %>
				<%= form.label :description, "2. Описание", :style=>'font-weight:bold' %><br />
				<%= form.text_area :description, :class=>'large' %>
					<p>Нужно поменять слова. Описание опроса может помочь Вам вспомнить с какой целью он был создан.</p>
				</div>
	</div>
	<!--<div class="four columns">
			<label for="selectProject">Выберите проект:</label>
			<select id="selectProject" style="width: 100%;">
				<option>Уровень удовлетворенности клиентов</option>
				<option>Другой какой-то проект</option>
				<option>Еще один проект</option>
			</select>
				<div class="row">
					<div class="three column">
						<img src="" alt="" style="width: 100%; height: 4.5em; background-color: #eaeaea;" />
					</div>
					<div class="nine columns">
						<p>Цели карьерного роста клиентов, их опыт работы и приоритеты. Для повышения качества тренингов.</p>
					</div>
				</div>
	</div>-->
</div>
<hr/>
<div class="row">
	<div class="four columns">
		<a href="#" class="small white radius button">Отмена</a>
	</div>
	<div class="four columns" style="text-align: center;">
		<%= form.submit "Сохранить", :class=>'nice radius button' %>
		<!--<a href="#" class="nice radius button">Сохранить</a>-->
	</div>
	<div class="four columns" style="text-align: right;">
		<a href="#" class="small white radius button">К вопросам&nbsp;<i class="icon">▶</i></a>
	</div>
</div>
				

app/views/surveys/_form_basic.html.erb
<div class="row">
	<div class="eight columns" style="background-color: #f4f4f4;">
				<div style="padding: 1% 4% 0; ">
					<%= form.label :title, "1. Название", :style=>'font-weight:bold' %><br />
				<%= form.text_field :title, :class=>'input-text' %>
				<%= form.label :description, "2. Описание", :style=>'font-weight:bold' %><br />
				<%= form.text_area :description, :class=>'large' %>
					<p>Нужно поменять слова. Описание опроса может помочь Вам вспомнить с какой целью он был создан.</p>
				</div>
	</div>
	<!--<div class="four columns">
			<label for="selectProject">Выберите проект:</label>
			<select id="selectProject" style="width: 100%;">
				<option>Уровень удовлетворенности клиентов</option>
				<option>Другой какой-то проект</option>
				<option>Еще один проект</option>
			</select>
				<div class="row">
					<div class="three column">
						<img src="" alt="" style="width: 100%; height: 4.5em; background-color: #eaeaea;" />
					</div>
					<div class="nine columns">
						<p>Цели карьерного роста клиентов, их опыт работы и приоритеты. Для повышения качества тренингов.</p>
					</div>
				</div>
	</div>-->
</div>
<hr/>
<div class="row">
	<div class="four columns">
		<%= link_to 'Отмена', surveys_path, :class=>'small white radius button' %>
	</div>
	<div class="four columns" style="text-align: center;">
		<%= form.submit "Сохранить", :class=>'nice radius button' %>
		<!--<a href="#" class="nice radius button">Сохранить</a>-->
	</div>
	<div class="four columns" style="text-align: right;">
		<%= link_to('activateTab()', :remote=>true,  :class=>'small white radius button') do %>
  				К вопросам&nbsp;<i class="icon">▶</i>
		<% end %>
	</div>
</div>
				

app/views/surveys/_form_questions.html.erb
<% curpage = curpage.to_i == 0 ? 1 : curpage.to_i %>
<div class="">
			<h3>Выберите шаблон</h3>
				</div>
				<hr />
				<div class="row">
					<div class="three columns">
					
						<div class="palette">
							<!--Если вдруг экран окажется совсем маленьким, то нужно добавлять полосу прокрутки. Примерно то же самое для айпада. Как вариант можно сделать раскрывающееся меню под вопросами-->
							<%= form.submit "Сохранить", :class=>'nice radius button' %>
							
							<!-- hidden input передаёт текущую страницу -->
							<input type="hidden" name="pagenumber" value="<%= curpage %>" />

							<h5 style="padding-top: 1.5em;">Инструменты</h5>
							<hr />
							<a href="#">Демографические данные</a>
							<hr />
							<ul>
								<!--Отсортировано по частоте использования-->
								<li><%= link_to 'Multiple Choice Question', new_survey_page_question_path(s, s.pages[curpage-1], :code=>'mc') %></li>
								<li><a href="#">Несколько вариантов ответа</a></li>
								<li><a href="#">Открытый вопрос</a></li>
								<li><a href="#">Матрица</a></li>
								<li><a href="#">Оценка</a></li>
							</ul>
							<hr />
							<ul>
								<!--Отсортировано по алфавиту, потому что нестандартные поля, не так часто используются-->
								<li><a href="#">Дата и время</a></li>
								<li><a href="#">Изображение</a></li>
								<li><a href="#">Ссылка</a></li>
								<li><a href="#">Текст</a></li>
								<li><a href="#">Числа</a></li>
							</ul>
							<hr />
							<a href="#">Логика пропуска</a>
						</div>
						
					
					</div>
					<div class="nine columns">
						<!--Добавление страницы, предпросмотр-->
						<div style="background-color: #f4f4f4; padding: 0.5em 1em 0; margin-bottom: 1em;">
							
							<div class="row">
								<div class="four columns">
									<%= link_to '+ Добавить страницу', new_survey_page_path(s.id), :class=>"white small radius button" %>
									<!-- <a href="#" class="white small radius button">+ Добавить страницу</a> -->
								</div>
								<div class="five columns">
									<!--Если слишком много страниц, то стоит добавить дропдаун-->
									<%= render 'paginator', :s => s, :pagenumber => curpage %>
								</div>
								<div class="three columns" style="text-align: right;"><a href="#" class="small white nice radius button">Предпросмотр</a></div>
							</div>
						
						</div>
						<!-- page content -->
						<div style="background-color: #f4f4f4; padding: 0.5em 1em 0; margin-bottom: 1em;">
							<%= render 'view_page', :page=>s.pages[curpage-1] if s.pages[curpage-1] %>
						</div>
						<!--Добавление страницы, предпросмотр-->
						<div style="background-color: #f4f4f4; padding: 0.5em 1em 0; margin-bottom: 1em;">
							
							<div class="row">
								<div class="four columns">
									<a href="#" class="white small radius button">+ Добавить страницу</a>
								</div>
								<div class="five columns">
									<!--Если слишком много страниц, то стоит добавить дропдаун-->
									<%#= render 'paginator', :s => s, :pagenumber => curpage %>
								</div>
								<div class="three columns" style="text-align: right;"><a href="#" class="small white nice radius button">Предпросмотр</a></div>
							</div>
						
						</div>
					</div>
				</div>
				
				<hr/>
				<div class="row">
					<div class="four columns">
						<a href="#" class="small white radius button">Отмена</a>
					</div>
					<div class="four columns" style="text-align: center;">
						<a href="#" class="nice radius button">Сохранить</a>
					</div>
					<div class="four columns" style="text-align: right;">
						<a href="#" class="small white radius button">К оформлению&nbsp;<i class="icon">▶</i></a>
					</div>
				</div>

app/views/surveys/_paginator.html.erb
<!-- unavailable: current_item, if current_item = start then unavailable start_link -->
<!-- unavailable: current_item, if current_item = end then unavailable end_link -->
<!-- current is curPage -->
<!-- two parameters: pages, pagenumber -->
<% pages = s.pages %>
<% pagenumber = pagenumber.to_i %>

<ul class="pagination" style="margin-bottom: 0;">
	  <% if pagenumber == 1 %>
	  	<li class="unavailable"><a href="#">&laquo;</a></li>
 	  <% else %>
 	  	<li><%= link_to '&laquo;'.html_safe , survey_edit_page_path(s, pagenumber-1) %></li>
	  <% end %>
	  <!-- 1... -->
	  <% if pagenumber-3 > 1 %>
	  	<li><%= link_to '1', survey_edit_page_path(s, 1) %></li>
	  	<li class="unavailable"><a href="#">&hellip;</a></li>
	  	<li><%= link_to pagenumber-2, survey_edit_page_path(s, pagenumber-2) %></li>
	  	<li><%= link_to pagenumber-1, survey_edit_page_path(s, pagenumber-1) %></li>
	  <% else %>
	  	 <% (1...pagenumber).each do |num| %>
	  		<li><%= link_to num, survey_edit_page_path(s, num) %></li>
	  	 <% end %>
	  <% end %>
	  

	  <!-- cur pages -->
	  <% if s.new_record? %>
	  	<li class="unavailable"><a href="#">1</a></li>
	  <% else %>
	  	<li class="current"><%= link_to pagenumber, survey_edit_page_path(s, pagenumber) %></li>
	  <% end %>
	  
	  
	    
	  <% if pagenumber + 3 < pages.length %>
	  	<!-- after cur page -->
	    <li><%= link_to pagenumber+1, survey_edit_page_path(s, pagenumber+1) %></li>
	    <li><%= link_to pagenumber+2, survey_edit_page_path(s, pagenumber+2) %></li>
	     
	  	<li class="unavailable"><a href="#">&hellip;</a></li>
	    <li><%= link_to pages.length, survey_edit_page_path(s, pages.length) %></li>
	  <% else %>
	  	 <% (pagenumber+1..pages.length).each do |num| %>
	  		  <li><%= link_to num, survey_edit_page_path(s, num) %></li>
	  	 <% end %>
	  <% end %>

	  <% if pagenumber == pages.length %>
	  	<li class="unavailable"><a href="">&raquo;</a></li>
 	  <% else %>
 	    <li><%= link_to '&raquo;'.html_safe, survey_edit_page_path(s, pagenumber+1) %></li>
 	  <% end %>
</ul>

app/views/surveys/_view_page.html.erb
<div class="row">
	<div class="four columns">
		<h3><%= page.title %></h3>
	</div>
	<div class="five columns">
		<p class="nice"> <%= page.description %> very very long descirption of not so interesting page because lorem ipsum dolor cit amit </p>
	</div>
	<div class="three columns" style="text-align: right;">
		<%= link_to 'Edit Page', edit_survey_page_path(page.survey, page), :class=> 'small green nice radius button' %>
	</div>
</div>

app/views/surveys/edit.html.erb
<%= form_for @survey, :html => { :class=>'nice' } do |f| %>
<div class="row">
			<div class="twelve columns">
				<h3>Создание опроса</h3>
				<dl class="tabs contained">
					<dd><a href="#simple1" class="active">Общие настройки</a></dd>
					<dd><a href="#simple2">Вопросы</a></dd>
					<dd><a href="#simple3">Оформление</a></dd>
					<dd><a href="#simple4">Публикация</a></dd>
				</dl>
				
				<ul class="tabs-content contained">
					<li class="active" id="simple1Tab">
						<%= render 'form_basic', :form => f, :s => @survey %>
					</li>
					<li id="simple2Tab">
						<%= render 'form_questions', :form => f, :s => @survey, :curpage => @curPage %>
					</li>
					<li id="simple3Tab">This is simple tab 3's content. It's, you know...okay.</li>
					<li id="simple4Tab">This is simple tab 3's content. It's, you know...okay.</li>
				</ul>
			</div>
		</div>
<% end %>

app/views/surveys/index.html.erb
<h1><%= @surveyTitle %></h1>
<%= form_tag(sa_path) do %>
	<% @questionList.each do |question| %>
		<p>
			<h6><%= question[:title] %></h6>
			<% question[:answers].each do |answer| %>
				<input type="radio" name="q_<%= question[:id] %>" value="<%= answer.to_s %>" /><%= answer.to_s %><br />
			<% end %>
		</p>
	<% end %>

	<%= button_to 'submit' %>
<% end %>

app/views/surveys/new.html.erb
<%= form_for @survey, :html => { :class=>'nice' } do |f| %>
<div class="row">
			<div class="twelve columns">
				<h3>Создание опроса</h3>
				<dl class="tabs contained">
					<dd><a href="#simple1" class="active">Общие настройки</a></dd>
					<dd><a href="#simple2">Вопросы</a></dd>
					<dd><a href="#simple3">Оформление</a></dd>
					<dd><a href="#simple4">Публикация</a></dd>
				</dl>
				
				<ul class="tabs-content contained">
					<li class="active" id="simple1Tab">
						<%= render 'form_basic', :form => f, :s => @survey %>
					</li>
					<li id="simple2Tab">
						<%= render 'form_questions', :form => f, :s => @survey unless @survey.new_record? %>
					</li>
					<li id="simple3Tab">This is simple tab 3's content. It's, you know...okay.</li>
					<li id="simple4Tab">This is simple tab 3's content. It's, you know...okay.</li>
				</ul>
			</div>
		</div>
<% end %>