config/routes.rb
AskmeModel::Application.routes.draw do
  root :to => 'respondents#index'

  devise_for :respondents, :controllers => { :sessions => "respondents/sessions", :registrations => "respondents/registrations", :omniauth_callbacks => "respondents/omniauth_callbacks" }
  devise_for :responds, :controller => "fake_questions"

  match 'profile' => 'respondents#show'
  match 'profile/edit/' => 'respondents#edit#:id', :as => "pr_edit"

  resources :respondents do
    resources :profiles do
      member do
        post 'social_demographic_settings', :as => :sd
        post 'business_settings', :as => :business
      end          
    end
  end

  match 'surveys/:id/edit/page/:pagenumber' => 'surveys#edit#:id', :as => "survey_edit_page"

  match 'submitAnswers' => 'fakeQuestions#submitAnswers', :as => 'sa'

  resources :surveys do
    resources :pages do
      resources :questions do 
        
      end
    end
  end










 

end

app/views/layouts/_navigation.html.erb
<div class="row">
	<div class="four columns">
		<h1 style="font-size: 1.6rem; font-weight: 800; color: white; white">
			<%= link_to 'Askme.kz', root_path %>
		</h1>
	</div>
	<div class="eight columns">
		<strong style="display: block; position: relative; bottom: 4px; line-height: 14px; margin: 0;  padding: 0; padding-left: 5px; float: right;">

			<% if respondent_signed_in? %>
					<%= link_to 'Change password or email', edit_respondent_registration_path, :class=>'small blue nice button' %>
			<% else %>
					<%= link_to('Sign up', new_respondent_registration_path) %>
			<% end %>
			<% if respondent_signed_in? %>
					<%= link_to('Logout', destroy_respondent_session_path, :method=>'delete') %>
			<% else %>
					<%= link_to('Sign in', new_respondent_session_path) %>
			<% end %>
		</strong>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AskmeModel</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 <script type="text/javascript">
  	jQuery(document).ready(function ($) {
   // code here
   		var page = <%= @curPage.nil? ? 0 : @curPage %>;
	  	if(page && <%= @actTab.nil? ? false : @actTab %>) {
	  		activateTab($('a[href=#simple2]'));
	  	}

	  	var new_record = <%= @survey.new_record? %>;
  		window.is_new_record = new_record;
  		function activateTab($tab) {
  			if (new_record) {
				alert("You should save your survey!")
				return false;
			}
			var $activeTab = $tab.closest('dl').find('a.active');
			var contentLocation = $tab.attr("href") + 'Tab';
			
			// Strip off the current url that IE adds
			contentLocation = contentLocation.replace(/^.+#/, '#');
			//Make Tab Active
			$activeTab.removeClass('active');
			$tab.addClass('active');

	    //Show Tab Content
			$(contentLocation).closest('.tabs-content').children('li').hide();
			$(contentLocation).css('display', 'block');
		}

	});
  </script>
</head>
<body>

	<div class="container" style="margin:0; padding:0;">
		<div class="row">
			<div class="twelve columns">
				<% if notice %>
				<div class="alert-box success">
					<p> <%= notice %></p>
					<p class="alert"><%= alert %></p>
				</div>
				<% end %> 
			</div>
		</div>
		<div id="headers" style="background: #222; border-bottom: solid 4px #00A5FF; padding: 15px 20px 13px 20px;" class="container">
			<%= render 'layouts/navigation' %>
		</div>
	</div>

		<div class="row">
			<div class="twelve columns"><%= yield %></div>
		</div>
	</div>
 
</body>
</html>